Version = "1.0.0.0"
Type = 1
Id = "cff0d8f7-f577-4b5d-a02f-002d30dad14b"
Name = "Arma Reforger"
Category = "Тактические"
ProcessName = "ArmaReforger(?:_BE|Steam(?:Diag)?)?\\.exe"
DescriptionShort = ""
DescriptionLong = "A clean tactical profile for Reforger's modern spatialization, reverb-heavy spaces, infantry combat, vehicles, helicopters, and team communication."
ImageSmall = "ImageSmallProfileAE9Personal"
ImageLarge = "ImageLargeProfileAE9Personal"
Product = "AE9"
CreatorName = "The Sound Blaster Team"
CreatorProfession = ""
Order = 100
SpeakerMethod = 0

[[Settings]]
Type = 0

[Settings.Surround]
Enable = true
Level = 0.25
Mode = 0

[Settings.Crystalizer]
Enable = true
Level = 0.18

[Settings.Bass]
Enable = true
Level = 0.2
XOver = 80
SubWooferGain = false

[Settings.SVM]
Enable = false
Level = 0.2
Mode = 0
PlusMode = 0

[Settings.DialogPlus]
Enable = true
Level = 0.15
Mode = 0

[Settings.Scout]
Enable = false
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
GraphicsEQEnable = false

[Settings.SBXMaster]
Enable = true
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false

[[Settings]]
Type = 1

[Settings.Surround]
Enable = true
Level = 0.42
Mode = 0

[Settings.Crystalizer]
Enable = true
Level = 0.18

[Settings.Bass]
Enable = true
Level = 0.24
XOver = 80
SubWooferGain = false

[Settings.SVM]
Enable = false
Level = 0.2
Mode = 0
PlusMode = 0

[Settings.DialogPlus]
Enable = true
Level = 0.15
Mode = 0

[Settings.Scout]
Enable = false
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
GraphicsEQEnable = false

[Settings.SBXMaster]
Enable = true
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
