Version = "1.0.0.0"
Type = 1
Id = "0fbc57f0-4b8b-42fb-982a-763ad830d2b4"
Name = "Black Myth: Wukong"
Category = "RPG и приключения"
ProcessName = "b1-Win64-Shipping\\.exe"
DescriptionShort = ""
DescriptionLong = "A cinematic action-RPG profile for staff impacts, transformations, mystical ambience, and bass-heavy boss encounters."
ImageSmall = "ImageSmallProfileAE9Personal"
ImageLarge = "ImageLargeProfileAE9Personal"
Product = "AE9"
CreatorName = "The Sound Blaster Team"
CreatorProfession = ""
Order = 100
SpeakerMethod = 0

[[Settings]]
Type = 0

[Settings.Surround]
Enable = true
Level = 0.6
Mode = 0

[Settings.Crystalizer]
Enable = true
Level = 0.3

[Settings.Bass]
Enable = true
Level = 0.28
XOver = 80
SubWooferGain = false

[Settings.SVM]
Enable = true
Level = 0.22
Mode = 0
PlusMode = 0

[Settings.DialogPlus]
Enable = true
Level = 0.28
Mode = 0

[Settings.Scout]
Enable = false
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
GraphicsEQEnable = false

[Settings.SBXMaster]
Enable = true
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false

[[Settings]]
Type = 1

[Settings.Surround]
Enable = true
Level = 0.7
Mode = 0

[Settings.Crystalizer]
Enable = true
Level = 0.3

[Settings.Bass]
Enable = true
Level = 0.32
XOver = 80
SubWooferGain = false

[Settings.SVM]
Enable = true
Level = 0.25
Mode = 0
PlusMode = 0

[Settings.DialogPlus]
Enable = true
Level = 0.28
Mode = 0

[Settings.Scout]
Enable = false
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
GraphicsEQEnable = false

[Settings.SBXMaster]
Enable = true
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
