Version = "1.0.0.0"
Type = 1
Id = "b117134e-cf09-434a-8025-97c672159cfa"
Name = "Call of Duty Infinite Warfare"
Category = "Шутеры"
ProcessName = "iw7_ship\\.exe"
DescriptionShort = ""
DescriptionLong = ""
ImageSmall = "ImageSmallProfileAE9Personal"
ImageLarge = "ImageLargeProfileAE9Personal"
Product = "AE9"
CreatorName = "The Sound Blaster Team"
CreatorProfession = ""
Order = 100
SpeakerMethod = 0

[[Settings]]
Type = 0

[Settings.Surround]
Enable = true
Level = 0.12
Mode = 0

[Settings.Crystalizer]
Enable = false
Level = 0.5

[Settings.Bass]
Enable = true
Level = 0.5
XOver = 80
SubWooferGain = false

[Settings.SVM]
Enable = true
Level = 0.3
Mode = 0
PlusMode = 0

[Settings.DialogPlus]
Enable = false
Level = 0.5
Mode = 0

[Settings.Scout]
Enable = false
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
GraphicsEQEnable = false

[Settings.SBXMaster]
Enable = true
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false

[[Settings]]
Type = 1

[Settings.Surround]
Enable = true
Level = 0.67
Mode = 0

[Settings.Crystalizer]
Enable = true
Level = 0.2

[Settings.Bass]
Enable = false
Level = 0.5
XOver = 80
SubWooferGain = false

[Settings.SVM]
Enable = false
Level = 0.74
Mode = 0
PlusMode = 0

[Settings.DialogPlus]
Enable = false
Level = 0.5
Mode = 0

[Settings.Scout]
Enable = false
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
GraphicsEQEnable = false

[Settings.SBXMaster]
Enable = true
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
