Version = "1.0.0.0"
Type = 1
Id = "f89bbe9b-206f-49a1-b275-b2b94cab47e9"
Name = "Hogwarts Legacy"
Category = "RPG и приключения"
ProcessName = "HogwartsLegacy\\.exe"
DescriptionShort = ""
DescriptionLong = "An open-world adventure profile tuned for spellcasting, castle reverb, orchestral score, and frequent character dialogue."
ImageSmall = "ImageSmallProfileAE9Personal"
ImageLarge = "ImageLargeProfileAE9Personal"
Product = "AE9"
CreatorName = "The Sound Blaster Team"
CreatorProfession = ""
Order = 100
SpeakerMethod = 0

[[Settings]]
Type = 0

[Settings.Surround]
Enable = true
Level = 0.5
Mode = 0

[Settings.Crystalizer]
Enable = true
Level = 0.25

[Settings.Bass]
Enable = true
Level = 0.2
XOver = 80
SubWooferGain = false

[Settings.SVM]
Enable = true
Level = 0.25
Mode = 0
PlusMode = 0

[Settings.DialogPlus]
Enable = true
Level = 0.3
Mode = 0

[Settings.Scout]
Enable = false
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
GraphicsEQEnable = false

[Settings.SBXMaster]
Enable = true
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false

[[Settings]]
Type = 1

[Settings.Surround]
Enable = true
Level = 0.6
Mode = 0

[Settings.Crystalizer]
Enable = true
Level = 0.25

[Settings.Bass]
Enable = true
Level = 0.25
XOver = 80
SubWooferGain = false

[Settings.SVM]
Enable = true
Level = 0.28
Mode = 0
PlusMode = 0

[Settings.DialogPlus]
Enable = true
Level = 0.3
Mode = 0

[Settings.Scout]
Enable = false
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
GraphicsEQEnable = false

[Settings.SBXMaster]
Enable = true
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
