Version = "1.0.0.0"
Type = 1
Id = "c8bcbe15-378b-407b-a9fd-793c7ff92e19"
Name = "Overwatch"
Category = "Шутеры"
ProcessName = "Overwatch\\.exe"
DescriptionShort = ""
DescriptionLong = ""
ImageSmall = "ImageSmallProfileAE9Personal"
ImageLarge = "ImageLargeProfileAE9Personal"
Product = "AE9"
CreatorName = "The Sound Blaster Team"
CreatorProfession = ""
Order = 100
SpeakerMethod = 0

[[Settings]]
Type = 0

[Settings.Surround]
Enable = false
Level = 0.67
Mode = 0

[Settings.Crystalizer]
Enable = true
Level = 0.3

[Settings.Bass]
Enable = true
Level = 0.5
XOver = 80
SubWooferGain = false

[Settings.SVM]
Enable = false
Level = 0.74
Mode = 0
PlusMode = 0

[Settings.DialogPlus]
Enable = false
Level = 0.5
Mode = 0

[Settings.Scout]
Enable = false
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
GraphicsEQEnable = false

[Settings.SBXMaster]
Enable = true
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false

[[Settings]]
Type = 1

[Settings.Surround]
Enable = true
Level = 0.67
Mode = 0

[Settings.Crystalizer]
Enable = true
Level = 0.2

[Settings.Bass]
Enable = false
Level = 0.5
XOver = 80
SubWooferGain = false

[Settings.SVM]
Enable = false
Level = 0.74
Mode = 0
PlusMode = 0

[Settings.DialogPlus]
Enable = false
Level = 0.5
Mode = 0

[Settings.Scout]
Enable = false
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
GraphicsEQEnable = false

[Settings.SBXMaster]
Enable = true
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
