Version = "1.0.0.0"
Type = 1
Id = "71628a8d-9393-4da9-b45b-52ea158c7227"
Name = "Ночь"
Category = "Общие"
DescriptionShort = ""
DescriptionLong = "Even when watching movies at night, all of the sonic essence ought to be untouched. I expect intelligent audio dynamics, unmuffled sound, and most importantly, an enjoyable movie."
ImageSmall = "ImageSmallProfileAE9Personal"
ImageLarge = "ImageLargeProfileAE9Personal"
Product = "AE9"
CreatorName = "The Sound Blaster Team"
CreatorProfession = "Audio Enthusiast"
Order = 40
SpeakerMethod = 0

[[Settings]]
Type = 0

[Settings.Surround]
Enable = true
Level = 0.67
Mode = 0

[Settings.Crystalizer]
Enable = true
Level = 0.55

[Settings.Bass]
Enable = true
Level = 0.2
XOver = 80
SubWooferGain = false

[Settings.SVM]
Enable = true
Level = 0.74
Mode = 2
PlusMode = 0

[Settings.DialogPlus]
Enable = true
Level = 0.3
Mode = 0

[Settings.Scout]
Enable = false
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
GraphicsEQEnable = false

[Settings.SBXMaster]
Enable = true
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false

[[Settings]]
Type = 1

[Settings.Surround]
Enable = true
Level = 0.67
Mode = 0

[Settings.Crystalizer]
Enable = true
Level = 0.55

[Settings.Bass]
Enable = true
Level = 0.2
XOver = 80
SubWooferGain = false

[Settings.SVM]
Enable = true
Level = 0
Mode = 2
PlusMode = 0

[Settings.DialogPlus]
Enable = true
Level = 0.3
Mode = 0

[Settings.Scout]
Enable = false
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
GraphicsEQEnable = false

[Settings.SBXMaster]
Enable = true
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
