Version = "1.0.0.0"
Type = 1
Id = "5089d75a-f6aa-45e2-b297-6caa218a56e9"
Name = "Ролевая игра"
Category = "Жанры"
DescriptionShort = ""
DescriptionLong = "Role-play in massively multi-player online games, be the main hero in fiction. From gaining XP through quests and combat to gaining new skills through leveling, hear the best as you journey through new lands, above a dynamic soundtrack."
ImageSmall = "ImageSmallProfileAE9Personal"
ImageLarge = "ImageLargeProfileAE9Personal"
Product = "AE9"
CreatorName = "The Sound Blaster Team"
CreatorProfession = ""
Order = 100
SpeakerMethod = 0

[[Settings]]
Type = 0

[Settings.Surround]
Enable = true
Level = 0.35
Mode = 0

[Settings.Crystalizer]
Enable = false
Level = 0.5

[Settings.Bass]
Enable = true
Level = 0.2
XOver = 80
SubWooferGain = false

[Settings.SVM]
Enable = true
Level = 0.3
Mode = 0
PlusMode = 0

[Settings.DialogPlus]
Enable = true
Level = 0.15
Mode = 0

[Settings.Scout]
Enable = false
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
GraphicsEQEnable = false

[Settings.SBXMaster]
Enable = true
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false

[[Settings]]
Type = 1

[Settings.Surround]
Enable = true
Level = 0.35
Mode = 0

[Settings.Crystalizer]
Enable = false
Level = 0.5

[Settings.Bass]
Enable = true
Level = 0.2
XOver = 80
SubWooferGain = false

[Settings.SVM]
Enable = true
Level = 0.3
Mode = 0
PlusMode = 0

[Settings.DialogPlus]
Enable = true
Level = 0.15
Mode = 0

[Settings.Scout]
Enable = false
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
GraphicsEQEnable = false

[Settings.SBXMaster]
Enable = true
SurroundEnable = false
CrystalizerEnable = false
XBassEnable = false
SVMEnable = false
DialogPlusEnable = false
